#-*- coding: utf-8 -*-
PORT_ERROR = u"端口号错误"
TCP_CREATE_FAILED = u"创建失败: 端口或地址不可用"
TCP_CLIENT_CONNECT_ERROR = u"TCP连接失败"
UDP_CLIENT_CONNECT_ERROR = u"UDP绑定本地端口失败"
CREATE_UDP_SERVER_FAILED = TCP_CREATE_FAILED