#-*- coding: utf-8 -*-
TCP_SERVER_FLAG = 0x00
TCP_CLIENT_FLAG = 0x10
UDP_SERVER_FLAG = 0x20

TCP_SERVER        = TCP_SERVER_FLAG | 0x01
TCP_CLIENT_REMOTE = TCP_SERVER_FLAG | 0x02
TCP_CLIENT_LOCAL  = TCP_CLIENT_FLAG | 0x10
UDP_SERVER        = UDP_SERVER_FLAG | 0x00 # it's just like a sever
UDP_CLIENT_REMOTE = UDP_SERVER_FLAG | 0x01
UDP_CLIENT_LOCAL  = UDP_SERVER_FLAG | 0x03
